<html>
  <head>
    <link rel="stylesheet" type="text/css" href="css/assign2.css">
    <style type="text/css">
    ul{

      list-style-image: url('images/icon8.png');
      font-size:12px;
    }
        /*ul{

            list-style-image: url('images/icon9.png');
            font-size:12px;
            }*/
    </style>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap Assignment</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <!-- 1111111111111111111111111111111111111111111111111111111111 -->
    <div class="container">
    
      <div class="container">
        <div class="row">
          <div class="col-md-6">
            <img class="section1-left-logo" src="images/foot_logo.png" alt="loading" height="60" width="300">
          </div>
          <div class="col-md-6">
            <div >
              <form id="tfnewsearch"  method="get" action="http://www.google.com">
                <span class="call">Call Us Today! (02) 9017 8413 </span>

                <input type="text" name="search_box" /><input type="submit"  id="image-button"/>
              </form>

              <!-- <div id="link1">
                <a style="color:#AAA4A4" href="#"> <span class="link">Home&nbsp;&nbsp;&nbsp;</span> </a>
                <a style="color:#AAA4A4" href="#"><span class="link">Dating blog&nbsp;&nbsp;&nbsp; </span></a>
                <a style="color:#AAA4A4" href="#"><span class="link">Who we help&nbsp;&nbsp;&nbsp;</span> </a>
                <a style="color:#AAA4A4" href="#"><span class="link">Why vital&nbsp;&nbsp;&nbsp;</span></a>
                <a style="color:#AAA4A4" href="#"><span class="link">Reviews&nbsp;&nbsp;&nbsp;</span> </a>
                <a style="color:#AAA4A4" href="#"><span class="link">Contact Us&nbsp;&nbsp;&nbsp;</span></a>                    
              </div> -->
              <div class="container">
                <ul class="nav nav-tabs">
                  <li class="active"><a href="#">Home</a></li>
                  <li><a href="#">Dating blog</a></li>
                  <li><a href="#">Who we help</a></li>
                  <li><a href="#">Why vital</a></li>
                  <li><a href="#">Reviews</a></li>
                  <li><a href="#">Contact Us</a></li>
                </ul>
                <br>
              </div>
            </div>
             
          </div>
        </div>
    </div>
    <!-- 2222222222222222222222222222222222222222222222222222222222 -->
    <div class="container">
      <div class="row">
        <div  class="section2img" class="section2">
          <div class="col-md-4">
            <img class="Logo1" src="images/icon5.png" alt="loading" height="100" width="50">
          </div>
          <div class="col-md-4">
            <font color="white"><font size="5">Lorem Ipsum is simply dummy text of the printing ind.</font></font>
          </div>
          <div class="col-md-4">
            <!-- <button class="button1" onclick="alert('Downloading...!') ">DOWNLOAD NOW!</button> -->
            <button  onclick="alert('Downloading...!') " class="btn btn-primary btn-lg sharp">DOWNLOAD NOW!</button>
          </div>
        </div>
      </div>
    </div>
    <!-- 33333333333333333333333333333333333333333333333333333333333333 -->
    <div class="container">
      <div class="row">
        <div class="col-md-6" >
          <!-- <button type="button" onclick="alert('Buffring...!')"></button> -->
          <div class="videobutton">
            <!-- <button id="myimage" onclick="alert('Buffering...!')"></button> -->
            <div id="play_button" ><button class="button2-A"><img src="images/video-play-btn.png" width="40px" height="30px"></button>
            </div>
          </div>
        </div>
        <div class="col-md-6">
          <div class="section3Text">
            <div id="text">
              <font color="Black"><font size="6">Loren Ipsum dolor sit posure</font></font><br>
              <font color="Black"><font size="6"> long dolor sit amet.</font></font></br>
              <font color="Black"><font size="6">It has survived not on?</font></font><br>
            </div>

          </div> 
          <div class="section3button2">
            <!-- <button class="button2" onclick="alert('Contacting...!')">Contact Us Now!</button> -->
            <!-- &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; -->
            <!-- <button class="button3">Contact us!</button> -->
            <button  onclick="alert('Downloading...!') " class="btn btn-primary btn-lg sharp">Contact Us!</button>

          </div>
        </div>
      </div>
    </div>
    <!-- 4444444444444444444444444444444444444444444444444444 -->
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <div class="section4Para">
            <h1>About Us</h1>
            <font size="4">It is a long established fact that a</font><br>
            <font size="4">reader will be distracted.</font><br><br>
            <font size="2"><strong> The point of using lorem Ipsum is</strong> that it has a more-or-less normal</font><br>
            <font size="2">button of letters,as opposed to using 'Content here, content here' making</font><br> <font size="2">look like readable English.</font><br><br>
            <font size="2"><strong>There are many variations of passages of </strong>lorem Ipsum available,but the</font><br>
            <font size="2">majority have suffered alteration in some form.</font><br><br>

            <img src="images/arrow1.png" alt="loading" height="16" width="16"><strong>200 years old. Richard Mc Client.</strong><br>

            <img src="images/arrow1.png" alt="loading" height="16" width="16"><strong>Discovered the undoutable source</strong><br>

            <img src="images/arrow1.png" alt="loading" height="16" width="16"><strong>Lorem ipsum dolor sit amet..</strong><br><br>

            <font size="2">remaining essentially unchanged.It was popularised in the 1960s with</font><br>
            <font size="2">the release sheets containing.</font><br><br>

            <!-- <button class="button2" onclick="alert('Contacting...!')">Contact Us Now!</button> -->
            <!-- <button class="button3">Contact us!</button> -->
            <button  onclick="alert('Downloading...!') " class="btn btn-primary btn-lg sharp">Contact Us!</button>       

          </div>


        </div>
        <div class="col-md-6">
          <div class="imgsection">
            <img  src="images/blog_image.jpg"  class="imageBorder" alt="loading" height="300" width="300">
          </div>

        </div>

      </div>
    </div>
    <!-- 5555555555555555555555555555555555555555555555555555555555 -->
           <!-- <div class="section5">
            
            
            <div class="section5-part1">

                    How  Vital Works

            </div>
            <div class="section5-part2">
                    Steps,Hop or Skip Your Way To Happiness.

            </div>
            <div class="section5-circle1">
                <img  src="images/n1.png"  class="" alt="loading" height="75" width="75">
                <img  src="images/dotted-line.png"  class="" alt="loading" height="2px" width="75">
                

            </div>
            <div class="section5-circle2">
                <img  src="images/n2.png"  class="" alt="loading" height="75" width="75">
                <img  src="images/dotted-line.png"  class="" alt="loading" height="2px" width="75">
                <img  src="images/n3.png"  class="" alt="loading" height="75" width="75">
                <img  src="images/dotted-line.png"  class="" alt="loading" height="2px" width="75">
                <img  src="images/n4.png"  class="" alt="loading" height="75" width="75">
                <img  src="images/dotted-line.png"  class="" alt="loading" height="2px" width="75">
                <img  src="images/n5.png"  class="" alt="loading" height="75" width="75">
                <img  src="images/dotted-line.png"  class="" alt="loading" height="2px" width="75">
                <img  src="images/n6.png"  class="" alt="loading" height="75" width="75">
            </div>
            


        </div> 
      -->    
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p id="section222-heading">How Vital Works<p>
            <p id="section222-heading2">Step, Hop and Skip Your Way To Happiness<p>
              <div class="images">
                <div class="img1">
                  <p id="step1">STEP</p>
                  <img src="images/n1.png" height="70px" width="70px">
                </div>

                <div class="img2">
                  <img src="images/dotted-line.png" width="50px">
                </div>

                <div class="img3">
                 <p id="step">STEP</p>
                 <img src="images/n2.png" height="70px" width="70px">
               </div>

               <div class="img4">
                <img src="images/dotted-line.png" width="50px">
              </div>

              <div class="img5">
                <p id="step">STEP</p>
                <img src="images/n3.png" height="70px" width="70px">
              </div>

              <div class="img6">
                <img src="images/dotted-line.png" width="50px">
              </div>

              <div class="img7">
                <p id="step">HOP</p>
                <img src="images/n4.png" height="70px" width="70px">
              </div>

              <div class="img8">
                <img src="images/dotted-line.png" width="50px">
              </div>   

              <div class="img9">
                <p id="step">HOP</p>
                <img src="images/n5.png" height="70px" width="70px">
              </div>
              <div class="img10">
                <img src="images/dotted-line.png">
              </div>
              <div class="img11">
                <p id="step">SKIP</p>
                <img src="images/n6.png" height="70px" width="70px">
              </div>
            </div>
            <div class="text-box">
              Pop into our office and meet as face to face..
        </div>
        </div>
      </div>
    </div>
    <!-- 666666666666666666666666666666666666666666666666666666 -->
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="section6top">
            <div class="section6top-para">
              <font size="4">Lorem Ipsum is simply dummy text of the printing and typecasting industry. lorem Ipsum has</font><br>
              <font size="4">been the industry's standard ever since the 1500's, when an unknown printer took a</font><br>
              <font size="4">galley of type and Scrambled it to make a type Specimen book.</font><br>
            </div>
          </div>
        </div>
          
          <div class="col-md-6">

            <div class="section6bottom-left">
              <div class="section6bottom-left-frame">
               <img id="img1" src="images/icon2.png" height="75px" width="75px">
               <h3 align="center">What is lorem Ipsum ?</h3>
               <div class="framepara">
                <font size="2">Lorem Ipsum is simply dummy text of the and</font></br>
                <font size="2">typesetting industry lorem Ipsum has been the</font></br>
                <font size="2">industrys standard dummy text ever since</font></br>
                <font size="2">the 1500s, when an unknown printer</font></br>
                <font size="2">took a gallery of type and scrambled.</font></br><br>

                <font size="2">it to make a type speciman book. It has Survived</font></br>
                <font size="2">not only five centuries, but also the leap into we</font></br>
                <font size="2">electronic typecasting,remaining essentially</font></br>
                <font size="2">unchanged.</font></br><br>

                <!-- <button class="button3">Contact us!</button> -->
                <button  onclick="alert('Downloading...!') " class="btn btn-primary btn-lg sharp">Contact Us!</button>
              </div>
            </div>

          </div>
          <div class="col-md-6">
            <div class="section6bottom-right-frame">
              <img id="img1" src="images/icon3.png" height="75px" width="75px">
              <h3 align="center">Where does it comes ?</h3>
              <div class="framepara">
                <font size="2">It has survived not only five centuries but</font></br>
                <font size="2">also the leap into electronic typecasting,remain-</font></br>
                <font size="2">ing essentially unchanged popularised.</font></br><br>

                <font size="2">contry to popular belif,forem</font></br>
                <font size="2">Ipsum is not simply random text It has </font></br><br>

                <font size="2">lroots in a piece of classicial Latin literature from</font></br>
                <font size="2">45BC, making it over 2000 years old number is</font></br>
                <font size="2">this Richard McClintock ?</font><br><br>

                <!-- <button class="button3">Contact us!</button> -->
                <button  onclick="alert('Downloading...!') " class="btn btn-primary btn-lg sharp">Contact Us!</button>
              </div>
            </div>

          </div>

          </div>
      
      </div>
    </div>
  </body>
  
</html>
